### ISSUE TITLE
Using SIGKILL does not allow programs to exit cleanly

### ISSUE THREAD

**Issue by khadoran** [Tinkerforge/red-brick-apid#1]
A process should not be killed by SIGKILL as it cannot be caught using sigaction() to cleanly exit (i.e. serializing persistent data).

Instead, it would be better to first try SIGINT or SIGTERM and give the program (a configurable) time to terminate. Only if that fails, SIGKILL could be used, i.e. assuming the program hangs.

**Comment by photron** [comment]
Yes, using just SIGKILL in the process_destroy() function is not the best approach here.

Whether or not this can be easily changed in the current architecture of redapid heavily depends on how long the wait time between SIGTERM and SIGKILL should be. Any suggestions on how long to wait here?

Also did you actually ran into problems because of this or did you come across this by just looking at the code?

**Comment by khadoran** [comment]
I encountered the problem by examing the logfile of my application which was missing the "application terminating." line that comes when pressing CTRL-C on the console where it stops its infinite main loop and does an exit(0). And after a little investigation, I realized that SIGKILL was sent. :)

For the brick viewer (which I was using to terminate my application), it might be possible to wait 5 seconds and then ask the user (wait 5s again, send SIGKILL, cancel) until (s)he choose either send SIGKILL or cancel.

It is difficult to say how long to wait, depends on how much an application does upon uninitialization. My application should quit within 1 or 2 seconds as it only writes a final log message to indicate that the application terminated normally (i.e. not by segfault, a C++ exception or anything alike). But it could be more, especially when database or network access is involved.

Maybe it can be solved by providing some scheduler API to react to control messages like suspend/resume, restart/reinitialize or quit?

**Comment by photron** [comment]
For Brick Viewer this is easy to change. At the moment the program "Kill" button in Brick Viewer just sends SIGKILL and I'd like to keep it that way. But I just added another button to send SIGTERM and named it "Exit". I choose "Exit" because for most people "Terminate" and "Kill" would sound the same if they are not familiar with the fine naming details of Unix signals. Both buttons just send their signal and do nothing else, no fancy timing which complicates things. If the program reacts normally to SIGTERM (what will be the common case) then the user will see the program state change immediately. If it doesn't then the user can choose to kill it. I think this covers the case you described as you can use the new "Exit" button with the next version of Brick Viewer, instead of the "Kill" button.

Then there is the SIGKILL that the redapid sends on its own in two situations:
1. If a program should be deleted then redapid will kill the current process of that program with SIGKILL. It does it this way, because the program delete call has to return as fast as possible. Otherwise Brick Viewer will run into a timeout.
2. If redapid is terminated itself it'll take all child processes with it using SIGKILL.

In this two situations I cannot easily add potentially several seconds of wait time per process due to the architecture of redapid. I've to look into this to see if there is a proper way to do this.

**Comment by photron** [comment]
Closing issue, because it has a solution and no response for several years.
